# SNMP Agent Configuration

system_mib_dir:
  linux: /usr/share/snmp/mibs
  darwin: /opt/homebrew/opt/net-snmp/share/snmp/mibs
  win32: c:\net-snmp\share\snmp\mibs


# List the MIBs to load (without extension)
# Example:
# mibs:
# - SNMPv2-MIB  # Standard system group (sysDescr, sysContact, etc.)
# - IF-MIB
# - HOST-RESOURCES-MIB
# - HOST-RESOURCES-TYPES
# - CISCO-ALARM-MIB

mibs:
  - SNMPv2-MIB  # Standard system group (sysDescr, sysContact, etc.)
  - IF-MIB
  - HOST-RESOURCES-MIB
  - HOST-RESOURCES-TYPES
  - CISCO-ALARM-MIB

